apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-app
  labels:
    app: order-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : order-service-app
  template:
    metadata:
      labels:
        app: order-service-app
    spec:
      containers:
        - name: order-service-app
          image: constan1/order-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9008
          env:
            - name: DB_USERNAME
              value: "order_client"
            - name: DB_PASSWORD
              value: "collapsedegregore11"
            - name: RABBIT_USERNAME
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"
            - name: ePassword
              value: "7566355151371252"


---

kind: Service
apiVersion: v1
metadata:
  name:  order-service-svc
spec:
  selector:
    app: order-service-app
  ports:
    - port:  80
      targetPort:  9008