apiVersion: apps/v1
kind: Deployment
metadata:
  name: transport-inquiry-service-app
  labels:
    app: transport-inquiry-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : transport-inquiry-service-app
  template:
    metadata:
      labels:
        app: transport-inquiry-service-app
    spec:
      containers:
        - name: transport-inquiry-service-app
          image: constan1/transport-inquiry-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9005
          env:
            - name: DB_USERNAME
              value: "inquiry_client"
            - name: DB_PASSWORD
              value: "TallGlassIsHere3141592654"
            - name: RABBIT_USERNAME
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"
            - name: ePassword
              value: "7566355151371252"


---

kind: Service
apiVersion: v1
metadata:
  name:  transport-inquiry-service-svc
spec:
  selector:
    app: transport-inquiry-service-app
  ports:
    - port:  80
      targetPort:  9005