apiVersion: apps/v1
kind: Deployment
metadata:
  name: transport-listing-service-app
  labels:
    app: transport-listing-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : transport-listing-service-app
  template:
    metadata:
      labels:
        app: transport-listing-service-app
    spec:
      containers:
        - name: transport-listing-service-app
          image: constan1/gregoryana-transport-listing-service:0.0.1
          imagePullPolicy: Always
          ports:
            - containerPort: 9006
          env:
            - name: DB_USERNAME
              value: "transport_listing_client"
            - name: DB_PASSWORD
              value: "MyBirthdayIsin191173541351"
            - name: RABBIT_USERNAME
              value: "guest"
            - name: RABBIT_PASSWORD
              value: "guest"


---

kind: Service
apiVersion: v1
metadata:
  name:  transport-listing-service-svc
spec:
  selector:
    app: transport-listing-service-app
  ports:
    - port:  80
      targetPort:  9006