


#server:
#  port: 9004
#
#
#spring:
#  application:
#    name: address-service

#eureka:
#  instance:
#    prefer-ip-address: true
#    hostname: eureka-0
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka

